### PR TITLE
Fix condition

### PR DESCRIPTION
**Pull request by llrs**
Many thanks for this package! I'm sure it will help a lot. 

Trying to use it I run into an error:

```
Error in is.call(x) && as.character(x[[1]]) %in% constructs : 
  'length(x) = 3 > 1' in coercion to 'logical(1)'
```

This is on the `%call_in%` function. This PR fixes this by assuming that if any character is in constructs is what it was meant.

### CODE REVIEW

**Comment by moodymudskipper** [comment]
Thanks! I think we should use `deparse1` instead of `as.character` here, and then no need for `any`. It will be a bit more robust

**Review by moodymudskipper — CHANGES_REQUESTED** [review]
Thanks, can we use deparse1 instead?

**Comment by llrs** [comment]
I use deparse1 (and backported it to close #68) but the local tests are failing

**Comment by moodymudskipper** [comment]
Thanks a lot I will take a look!

**Comment by moodymudskipper** [comment]
Thanks!

**Pull request merged**
